import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";


const spartan = League_Spartan({ 
  subsets: ["latin"],
  weight: ['300', "400", '500', '600', '700'],
  variable: '--font-spartan-sans'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spartan.variable} antialiased`}
      >
       
        {children}
      </body>
    </html>
  );
}
